apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-internal-cert
  namespace: vaultwarden
spec:
  secretName: vaultwarden-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - vault.glavanet.local
    - vault.local
  commonName: vault.glavanet.local
  duration: 2160h  # 90 days
  renewBefore: 360h  # 15 days before expiry
