---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguardhome-internal-cert
  namespace: adguardhome
spec:
  secretName: adguardhome-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - adguard.local.example.com
    - adguardhome.local
  commonName: adguard.local.example.com
  duration: 2160h  # 90 days
  renewBefore: 360h  # 15 days before expiry
