apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguardhome
  namespace: adguardhome
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: adguard.glavanet.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adguardhome-web
            port:
              number: 80
  tls:
  - hosts:
    - adguard.glavanet.local
    secretName: adguardhome-tls