---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificate-internal
  namespace: default
spec:
  secretName: test-internal-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - traefik.local.example.com
    - test.internal.local
  commonName: test.internal.local
